import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap"
});


export const metadata = {
  title: "My First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/globe.svg" />
      </head>
      <body className={`${poppins.className} bg-black text-white w-screen h-screen`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
